# Generated by Django 3.2.9 on 2021-11-22 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0002_rename_users_usertree'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTree',
            new_name='UserNode',
        ),
    ]
