# Generated by Django 3.2.9 on 2021-11-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20211123_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernode',
            name='CID',
        ),
        migrations.AddField(
            model_name='usernode',
            name='PID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.usernode'),
        ),
    ]
