# Generated by Django 3.2.9 on 2021-11-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20211124_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernode',
            name='PID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.usernode'),
        ),
    ]
