# Generated by Django 3.2.9 on 2021-11-24 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0008_alter_usernode_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernode',
            name='PID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PID', to=settings.AUTH_USER_MODEL),
        ),
    ]
