# Generated by Django 3.2.9 on 2021-11-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_usernode_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernode',
            name='Position',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Employee', 'Employee')], max_length=25, null=True),
        ),
    ]
