# Generated by Django 3.2.9 on 2021-11-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_usernode_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernode',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
