# Generated by Django 3.2.9 on 2021-11-25 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0011_alter_usernode_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(default=0)),
                ('ModeOfPayment', models.SmallIntegerField(choices=[(1, 'BKash'), (2, 'Nagad'), (3, 'Bank A/C'), (4, 'Cash')], default=1)),
                ('AgentName', models.CharField(blank=True, max_length=150, null=True)),
                ('SalesID', models.CharField(blank=True, max_length=150, null=True)),
                ('Note', models.CharField(blank=True, max_length=200, null=True)),
                ('Accept', models.BooleanField(default=False)),
                ('_init_Accept', models.BooleanField(default=False)),
                ('_init_delete', models.BooleanField(default=False)),
                ('Sender', phonenumber_field.modelfields.PhoneNumberField(help_text='You must add +88 for operations', max_length=100, region=None)),
                ('Receiver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preReceiver', to='Users.usernode')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('ImportantText', models.CharField(blank=True, max_length=200, null=True)),
                ('Note', models.TextField(blank=True, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Receiver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.usernode')),
                ('Sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.saledetails')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReminderTime', models.DateTimeField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreOrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuyerName', models.CharField(blank=True, max_length=150, null=True)),
                ('BuyerPhone', phonenumber_field.modelfields.PhoneNumberField(help_text='You must add +88 for operations', max_length=100, region=None)),
                ('ProductNote', models.TextField(help_text='Use code for product for better search result')),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DueList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuyerName', models.CharField(blank=True, max_length=150, null=True)),
                ('BuyerPhone', phonenumber_field.modelfields.PhoneNumberField(help_text='You must add +88 for operations', max_length=100, region=None)),
                ('ProductNote', models.TextField(help_text='Use code for product for better search result')),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
