# Generated by Django 3.2.9 on 2021-11-27 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0012_duelist_permissiontable_preorderlist_reminder_saledetails_saletransfer_transactiondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', max_length=300, null=True, unique=True)),
                ('Show', models.BooleanField(default=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DebitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', max_length=300, null=True, unique=True)),
                ('Show', models.BooleanField(default=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='saledetails',
            name='TrxID',
            field=models.CharField(default='Type Transaction id for your transaction', max_length=156),
        ),
        migrations.CreateModel(
            name='DebitSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', max_length=300, null=True, unique=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.debitcategory')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Method', models.SmallIntegerField(choices=[(1, 'BKash'), (2, 'Nagad'), (3, 'Bank A/C'), (4, 'Cash')])),
                ('Note', models.TextField(blank=True, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Reason', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.debitsubcategory')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CreditSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', max_length=300, null=True, unique=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.creditcategory')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Method', models.SmallIntegerField(choices=[(1, 'BKash'), (2, 'Nagad'), (3, 'Bank A/C'), (4, 'Cash')])),
                ('Note', models.TextField(blank=True, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.creditsubcategory')),
                ('User', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BalanceTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accept', models.BooleanField(default=False)),
                ('Method', models.SmallIntegerField(choices=[(1, 'BKash'), (2, 'Nagad'), (3, 'Bank A/C'), (4, 'Cash')])),
                ('Amount', models.IntegerField()),
                ('Note', models.CharField(blank=True, max_length=150, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Receiver', to=settings.AUTH_USER_MODEL)),
                ('User', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.IntegerField()),
                ('DebitOrCredit', models.BooleanField(choices=[(True, 'Credit'), (False, 'Debit')])),
                ('Method', models.SmallIntegerField(choices=[(1, 'BKash'), (2, 'Nagad'), (3, 'Bank A/C'), (4, 'Cash')])),
                ('Note', models.CharField(blank=True, max_length=200, null=True)),
                ('SubCat', models.CharField(blank=True, max_length=50, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
