# Generated by Django 3.2.9 on 2021-11-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_auto_20211127_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetails',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.companydetails'),
        ),
    ]
