# Generated by Django 3.2.9 on 2021-11-28 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_saledetails_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetails',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
