# Generated by Django 3.2.9 on 2021-11-28 09:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_saledetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetails',
            name='Sender',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='You must add +88 for operations', max_length=100, null=True, region=None),
        ),
    ]
