# Generated by Django 3.2.9 on 2021-11-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_alter_saledetails_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.companydetails'),
        ),
        migrations.AddField(
            model_name='debit',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.companydetails'),
        ),
    ]
