# Generated by Django 3.2.9 on 2021-12-06 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0021_auto_20211206_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetails',
            name='Receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preReceiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
