# Generated by Django 3.2.9 on 2021-12-06 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0022_alter_saledetails_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcategory',
            name='Creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Credit_Creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitcategory',
            name='Creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Debit_Creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitcategory',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
