{'008': {'identifier': '008', 'title': 'Intro to CS is the best course ever', 'created': '2021-09-01',
                  'modified': None, 'authors': [('Ponce', 'Marcelo'), ('Tafliovich', 'Anya Y.')],
                  'abstract': ' We present clear evidence that Introduction to Computer Science is the best course.'},
          '031': {'identifier': '031', 'title': 'Calculus is the best course ever', 'created': None,
                  'modified': '2021-09-02', 'authors': ['Breuss', 'Nataliya'],
                  'abstract': ' We discuss the reasons why Calculus I is the best course.'},
          '067': {'identifier': '067', 'title': 'Discrete Mathematics is the best course ever', 'created': '2021-09-02',
                  'modified': '2021-10-01', 'authors': [('Pancer', 'Richard'), ('Bretscher', 'Anna')],
                  'abstract': '  We explain why Discrete Mathematics is the best course of all times.'},
          '827': {'identifier': '827', 'title': 'University of Toronto is the best university', 'created': '2021-08-20',
                  'modified': '2021-10-02',
                  'authors': [('Ponce', 'Marcelo'), ('Bretscher', 'Anna'), ('Tafliovich', 'Anya Y.')],
                  'abstract': ' We show a formal proof that the University of Toronto is the best university.'},
          '042': {'identifier': '042', 'title': None, 'created': '2021-05-04', 'modified': '2021-05-05', 'authors': [],
                  'abstract': ' This is a very strange article with no title and no authors.'}}